name: DESTROY
env:
  EB_APPLICATION_NAME       : "test"
  AWS_REGION_NAME           : "us-east-1"


on:
  pull_request:
    types: [ closed ]

jobs:
 my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Get EB CLI version
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade

      - name: Initilazed CLI
        run: eb init ${{ env.EB_APPLICATION_NAME }}-${{ github.head_ref }}-app -p "64bit Amazon Linux 2 v3.3.8 running Python 3.8" --region ${{ env.AWS_REGION_NAME }}

      - name: Destroy
        run: eb terminate ${{ env.EB_APPLICATION_NAME }}-${{ github.head_ref }}-env --force

      - name: Delete S3 bucket
        run: aws s3 rb s3://test.${{ github.head_ref }}.bucket --force